### ISSUE TITLE
Linking issue with assimp & rt

### ISSUE THREAD

**Issue by Tobias-Fischer** [conda-forge/assimp-feedstock#14] opened 2020-12-02 01:04 UTC
When trying to build rviz in the robostack ros-noetic pipeline, I am running into this issue (see https://dev.azure.com/roboforge/ros_pipelines/_build/results?buildId=932&view=logs&j=837f1829-4336-5db1-1bb2-3164775d7cf9&t=837f1829-4336-5db1-1bb2-3164775d7cf9):

```
ninja: error: '/home/conda/feedstock_root/build_artifacts/assimp_1602927892273/_build_env/x86_64-conda-linux-gnu/sysroot/usr/lib/librt.so', needed by 'devel/lib/librviz.so', missing and no known rule to make it
```

@wolfv @traversaro any clue what this could be (and how to fix it)?

**Comment by Tobias-Fischer** [comment] 2020-12-02 01:04
I guess this is related to https://github.com/conda-forge/assimp-feedstock/pull/13

**Comment by Tobias-Fischer** [comment] 2020-12-02 04:45
Indeed the value is hardcoded in the assimpTargets.cmake:
```
set_target_properties(assimp::assimp PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<\$<NOT:\$<CONFIG:DEBUG>>:/home/conda/feedstock_root/build_artifacts/assimp_1602927892273/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/libz.so>;\$<\$<CONFIG:DEBUG>:/home/conda/feedstock_root/build_artifacts/assimp_1602927892273/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/libz.so>;assimp::IrrXML;/home/conda/feedstock_root/build_artifacts/assimp_1602927892273/_build_env/x86_64-conda-linux-gnu/sysroot/usr/lib/librt.so"
)
```

**Comment by traversaro** [comment] 2020-12-02 07:37
Interesting, I think for some reason the hardcoded zlib location is correctly relocated by conda installation scripts, while the librt no, and probably I did not notice that as I was working on Windows. I can look into that this evening (CET), to avoid future regressions probably it is a good idea to add a test step to the recipe.

**Comment by traversaro** [comment] 2020-12-02 07:44
As a quick fix, probably patching the following lines: 
* https://github.com/assimp/assimp/blob/v5.0.1/code/CMakeLists.txt#L1221
* https://github.com/assimp/assimp/blob/v5.0.1/code/CMakeLists.txt#L1014

to just be `if(FALSE)` should be sufficient to fix the problem, at the cost of disable some (compression?) features in the gltf parser.

**Comment by wolfv** [comment] 2020-12-02 08:17
yes, linking rt is slightly tricky since it's referenced from the system and present in the build-environment (as opposed to the host-environment). I think this might be why the replacement doesn't work. 
The rt library symlink is usually in `$BUILD_PREFIX/x86_64_gnu_linux_sysroot/lib/rt.so` or something similar.

Linking to rt should be done by just linking `rt` without any path, and then it should work. We have some fixes to disable hard-coded path to rt in catkin's cmake as well (also `threads` and `dl`).

**Comment by traversaro** [comment] 2020-12-02 08:23
In that case, probably the correct patch is then to change 
https://github.com/assimp/assimp/blob/v5.0.1/code/CMakeLists.txt#L1222
to 
~~~
  TARGET_LINK_LIBRARIES(assimp rt)
~~~

**Comment by wolfv** [comment] 2020-12-02 08:24
yes! Let's see who get's there earlier :)

**Comment by traversaro** [comment] 2020-12-02 19:18
This should be fixed by https://github.com/conda-forge/assimp-feedstock/pull/15 . I added https://github.com/conda-forge/assimp-feedstock/pull/16 to avoid future regressions.

**Closed** 2020-12-02 22:17 UTC

**Comment by traversaro** [comment] 2021-12-09 08:26
There was a regression related to this, and this was not detected for some reason by https://github.com/conda-forge/assimp-feedstock/pull/21 .
