### ISSUE TITLE
Big archive for Linux

### ISSUE THREAD

**Issue by jcarpent** [conda-forge/assimp-feedstock#18] opened 2021-07-29 10:24 UTC
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

For Linux systems, it appears that the conda archive size is very huge when compared to OSX or Windows (https://anaconda.org/conda-forge/assimp/files). It seems this is related to the size of the `libassimp.so.5.0.0`file.
Do you know why @traversaro @wolfv?

Thanks in advance,
Best,

Justin

**Comment by traversaro** [comment] 2021-07-29 12:09
I quicky checked on Debian, and there the size of the library is in the same order of magnitue to the Windows or OSX one for conda-forge, i.e. ~12 MB for Debian/Linux (see https://packages.debian.org/sid/libassimp5), while ~7 MB for Windows/Conda, as opposed to ~250 MB for Linux on conda. I need to check more in details.

**Comment by jcarpent** [comment] 2021-07-29 12:19
@traversaro Thanks for the quick feedback.

Best,
Justin

**Comment by traversaro** [comment] 2021-07-29 12:22
I checked with [bloaty](https://github.com/google/bloaty) what is taking so much size on Deb vs Conda, and this are the results:
~~~
straversaro@IITICUBLAP102:~/assimp_ws$ ../bloaty/build/bloaty ./deb/usr/lib/x86_64-linux-gnu/libassimp.so.5.0.0
    FILE SIZE        VM SIZE
 --------------  --------------
  55.2%  6.68Mi  55.0%  6.68Mi    .text
  16.0%  1.93Mi  15.9%  1.93Mi    .rela.dyn
  12.3%  1.49Mi  12.3%  1.49Mi    .data.rel.ro
   7.0%   870Ki   7.0%   870Ki    .eh_frame
   5.1%   636Ki   5.1%   636Ki    .rodata
   2.1%   264Ki   2.1%   264Ki    .gcc_except_table
   1.5%   189Ki   1.5%   189Ki    .eh_frame_hdr
   0.0%       0   0.4%  46.7Ki    .bss
   0.2%  26.5Ki   0.2%  26.5Ki    .dynstr
   0.1%  16.7Ki   0.1%  16.7Ki    .dynsym
   0.1%  9.34Ki   0.1%  9.28Ki    .rela.plt
   0.1%  7.63Ki   0.1%  7.57Ki    .data
   0.1%  6.27Ki   0.0%  6.20Ki    .plt
   0.0%  5.89Ki   0.0%       0    [Unmapped]
   0.0%  3.91Ki   0.0%  3.85Ki    .got
   0.0%  3.30Ki   0.0%  3.23Ki    .gnu.hash
   0.0%  1.45Ki   0.0%  1.39Ki    .gnu.version
   0.0%  1.33Ki   0.0%     433    [10 Others]
   0.0%     640   0.0%     576    .dynamic
   0.0%     568   0.0%     568    [LOAD #0 [R]]
   0.0%     512   0.0%     448    .gnu.version_r
 100.0%  12.1Mi 100.0%  12.1Mi    TOTAL
straversaro@IITICUBLAP102:~/assimp_ws$ ../bloaty/build/bloaty ./conda/lib/libassimp.so.5.0.0
    FILE SIZE        VM SIZE
 --------------  --------------
  38.4%  91.6Mi   0.0%       0    .debug_info
  31.2%  74.3Mi   0.0%       0    .debug_loc
  12.4%  29.6Mi   0.0%       0    .debug_str
   5.6%  13.3Mi   0.0%       0    .debug_ranges
   5.0%  11.9Mi   0.0%       0    .debug_line
   2.9%  6.94Mi  56.2%  6.94Mi    .text
   1.2%  2.85Mi   0.0%       0    .strtab
   0.8%  1.95Mi  15.8%  1.95Mi    .rela.dyn
   0.6%  1.49Mi  12.1%  1.49Mi    .data.rel.ro
   0.4%  1.05Mi   0.0%       0    .debug_abbrev
   0.4%  1002Ki   0.0%       0    .symtab
   0.3%   840Ki   6.6%   840Ki    .eh_frame
   0.2%   550Ki   4.4%   550Ki    .rodata
   0.1%   312Ki   0.0%       0    .debug_aranges
   0.1%   251Ki   2.0%   251Ki    .gcc_except_table
   0.1%   181Ki   1.4%   181Ki    .eh_frame_hdr
   0.0%  72.0Ki   0.6%  72.0Ki    .dynstr
   0.0%       0   0.4%  46.8Ki    .bss
   0.0%  36.9Ki   0.2%  27.9Ki    [19 Others]
   0.0%  30.7Ki   0.2%  30.7Ki    .dynsym
   0.0%  9.18Ki   0.1%  9.12Ki    .gnu.hash
 100.0%   238Mi 100.0%  12.3Mi    TOTAL
~~~

It seems that most of the size in conda is taken by debug symbols, even if assimp is compiled in Release mode (see https://github.com/conda-forge/assimp-feedstock/blob/master/recipe/build.sh#L7).

**Comment by traversaro** [comment] 2021-07-29 12:24
I checked if Debian patches had something changing the behaviour in this case, but I could not find anything that was immediatly relevant: https://sources.debian.org/patches/assimp/5.0.1%7Eds0-2/ .

**Comment by traversaro** [comment] 2021-07-29 12:48
The problem is that assimp 5.0.1 defines `-g` for all type of builds (including Release) in https://github.com/assimp/assimp/blob/v5.0.1/CMakeLists.txt#L245, but only for GCC (hence why the problem is just on Linux for us). Latest master commit is not affected as the bug was fixed by https://github.com/assimp/assimp/pull/3173 .

**Comment by traversaro** [comment] 2021-07-29 12:53
A fix is provided in https://github.com/conda-forge/assimp-feedstock/pull/20 .

**Comment by jmirabel** [comment] 2021-07-29 13:38
Any reason to patch this here rather than fixing it in assimp directly ?

**Comment by jmirabel** [comment] 2021-07-29 13:39
Oh, sorry, I misread your answer. It's already solved.

**Closed** 2021-07-29 14:32 UTC

**Comment by wolfv** [comment] 2021-07-29 19:24
Maybe Debian automatically strips binaries as they have split packages for debug symbols
